<#
.SYNOPSIS
  CIS Microsoft Windows Server 2025 STAND-ALONE Benchmark v1.0.0 - Level 1
  Administrative Template / registry-backed settings (sections 18-19).
.DESCRIPTION
  Data only - dot-source this file to load $CISStandaloneRegistry.
  Generated from the Stand-alone benchmark PDF. IDs are STAND-ALONE numbering and do
  not correspond to the Member/DC package in RegistrySettings.ps1.

  Scope field: MS = machine (HKLM), USER = per-user (HKU\[USER SID] -> HKCU).
.NOTES
  Settings the benchmark does not express as a single registry value (lists, SDDL,
  multi-value policies) are NOT here - see ExceptionsAndManualSteps.md section 4.
#>

$CISStandaloneRegistry = @(
  @{ Id="18.1.1.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\Personalization"; Name="NoLockScreenCamera"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Prevent enabling lock screen camera' is set to 'Enabled'
  @{ Id="18.1.1.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\Personalization"; Name="NoLockScreenSlideshow"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Prevent enabling lock screen slide show' is set to 'Enabled'
  @{ Id="18.1.2.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\InputPersonalization"; Name="AllowInputPersonalization"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Allow users to enable online speech recognition services' is set to 'Disabled'
  @{ Id="18.4.1"; Key="HKLM\SYSTEM\CurrentControlSet\Services\mrxsmb10"; Name="Start"; Type="DWord"; Value=4; Scope="MS" }  # Ensure 'Configure SMB v1 client driver' is set to 'Enabled: Disable driver (recommended)
  @{ Id="18.4.2"; Key="HKLM\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters"; Name="SMB1"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Configure SMB v1 server' is set to 'Disabled'
  @{ Id="18.4.4"; Key="HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\kernel"; Name="DisableExceptionChainValidation"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Enable Structured Exception Handling Overwrite Protection (SEHOP)' is set to 'En
  @{ Id="18.4.5"; Key="HKLM\SYSTEM\CurrentControlSet\Services\NetBT\Parameters"; Name="NodeType"; Type="DWord"; Value=2; Scope="MS" }  # Ensure 'NetBT NodeType configuration' is set to 'Enabled: P-node (recommended)'
  @{ Id="18.5.1"; Key="HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon"; Name="AutoAdminLogon"; Type="String"; Value="0"; Scope="MS" }  # Ensure 'MSS: (AutoAdminLogon) Enable Automatic Logon' is set to 'Disabled'
  @{ Id="18.5.2"; Key="HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters"; Name="DisableIPSourceRouting"; Type="DWord"; Value=2; Scope="MS" }  # Ensure 'MSS: (DisableIPSourceRouting IPv6) IP source routing protection level' is set to
  @{ Id="18.5.3"; Key="HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters"; Name="DisableIPSourceRouting"; Type="DWord"; Value=2; Scope="MS" }  # Ensure 'MSS: (DisableIPSourceRouting) IP source routing protection level' is set to 'Ena
  @{ Id="18.5.4"; Key="HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters"; Name="EnableICMPRedirect"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'MSS: (EnableICMPRedirect) Allow ICMP redirects to override OSPF generated routes
  @{ Id="18.5.6"; Key="HKLM\SYSTEM\CurrentControlSet\Services\NetBT\Parameters"; Name="NoNameReleaseOnDemand"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'MSS: (NoNameReleaseOnDemand) Allow the computer to ignore NetBIOS name release r
  @{ Id="18.5.8"; Key="HKLM\SYSTEM\CurrentControlSet\Control\Session Manager"; Name="SafeDllSearchMode"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'MSS: (SafeDllSearchMode) Enable Safe DLL search mode' is set to 'Enabled'
  @{ Id="18.5.9"; Key="HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon"; Name="ScreenSaverGracePeriod"; Type="String"; Value="5"; Scope="MS" }  # Ensure 'MSS: (ScreenSaverGracePeriod) The time in seconds before the screen saver grace 
  @{ Id="18.5.12"; Key="HKLM\SYSTEM\CurrentControlSet\Services\Eventlog\Security"; Name="WarningLevel"; Type="DWord"; Value=90; Scope="MS" }  # Ensure 'MSS: (WarningLevel) Percentage threshold for the security event log at which the
  @{ Id="18.6.4.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient"; Name="EnableMDNS"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Configure multicast DNS (mDNS) protocol' is set to 'Disabled'
  @{ Id="18.6.7.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\LanmanServer"; Name="AuditClientDoesNotSupportEncryption"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Audit client does not support encryption' is set to 'Enabled'
  @{ Id="18.6.7.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\LanmanServer"; Name="AuditClientDoesNotSupportSigning"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Audit client does not support signing' is set to 'Enabled'
  @{ Id="18.6.7.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\LanmanServer"; Name="AuditInsecureGuestLogon"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Audit insecure guest logon' is set to 'Enabled'
  @{ Id="18.6.7.4"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\LanmanServer"; Name="EnableAuthRateLimiter"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Enable authentication rate limiter' is set to 'Enabled'
  @{ Id="18.6.7.5"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\Bowser"; Name="EnableMailslots"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Enable remote mailslots' is set to 'Disabled'
  @{ Id="18.6.7.6"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\LanmanServer"; Name="MinSmb2Dialect"; Type="DWord"; Value=785; Scope="MS" }  # Ensure 'Mandate the minimum version of SMB' is set to 'Enabled: 3.1.1'
  @{ Id="18.6.7.7"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\LanmanServer"; Name="InvalidAuthenticationDelayTimeInMs"; Type="DWord"; Value=2000; Scope="MS" }  # Ensure 'Set authentication rate limiter delay (milliseconds)' is set to 'Enabled: 2000' 
  @{ Id="18.6.8.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\LanmanWorkstation"; Name="AuditInsecureGuestLogon"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Audit insecure guest logon' is set to 'Enabled'
  @{ Id="18.6.8.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\LanmanWorkstation"; Name="AuditServerDoesNotSupportEncryption"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Audit server does not support encryption' is set to 'Enabled'
  @{ Id="18.6.8.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\LanmanWorkstation"; Name="AuditServerDoesNotSupportSigning"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Audit server does not support signing' is set to 'Enabled'
  @{ Id="18.6.8.4"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\LanmanWorkstation"; Name="AllowInsecureGuestAuth"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Enable insecure guest logons' is set to 'Disabled'
  @{ Id="18.6.8.5"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\NetworkProvider"; Name="EnableMailslots"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Enable remote mailslots' is set to 'Disabled'
  @{ Id="18.6.8.6"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\LanmanWorkstation"; Name="MinSmb2Dialect"; Type="DWord"; Value=785; Scope="MS" }  # Ensure 'Mandate the minimum version of SMB' is set to 'Enabled: 3.1.1'
  @{ Id="18.6.8.7"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\LanmanWorkstation"; Name="RequireEncryption"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Require Encryption' is set to 'Enabled'
  @{ Id="18.6.11.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\Network Connections"; Name="NC_AllowNetBridge_NLA"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Prohibit installation and configuration of Network Bridge on your DNS domain net
  @{ Id="18.6.11.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\Network Connections"; Name="NC_ShowSharedAccessUI"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Prohibit use of Internet Connection Sharing on your DNS domain network' is set t
  @{ Id="18.6.21.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\WcmSvc\GroupPolicy"; Name="fMinimizeConnections"; Type="DWord"; Value=3; Scope="MS" }  # Ensure 'Minimize the number of simultaneous connections to the Internet or a Windows Dom
  @{ Id="18.7.1"; Key="HKLM\Software\Policies\Microsoft\Windows NT\Printers"; Name="RegisterSpoolerRemoteRpcEndPoint"; Type="DWord"; Value=2; Scope="MS" }  # Ensure 'Allow Print Spooler to accept client connections' is set to 'Disabled'
  @{ Id="18.7.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Printers"; Name="RedirectionguardPolicy"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Configure Redirection Guard' is set to 'Enabled: Redirection Guard Enabled'
  @{ Id="18.7.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Printers\RPC"; Name="RpcUseNamedPipeProtocol"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Configure RPC connection settings: Protocol to use for outgoing RPC connections'
  @{ Id="18.7.4"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Printers\RPC"; Name="RpcAuthentication"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Configure RPC connection settings: Use authentication for outgoing RPC connectio
  @{ Id="18.7.5"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Printers\RPC"; Name="RpcProtocols"; Type="DWord"; Value=5; Scope="MS" }  # Ensure 'Configure RPC listener settings: Protocols to allow for incoming RPC connections
  @{ Id="18.7.6"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Printers\RPC"; Name="ForceKerberosForRpc"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Configure RPC listener settings: Authentication protocol to use for incoming RPC
  @{ Id="18.7.7"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Printers\RPC"; Name="RpcTcpPort"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Configure RPC over TCP port' is set to 'Enabled: 0'
  @{ Id="18.7.8"; Key="HKLM\SYSTEM\CurrentControlSet\Control\Print"; Name="RpcAuthnLevelPrivacyEnabled"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Configure RPC packet level privacy setting for incoming connections' is set to '
  @{ Id="18.7.10"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Printers\PointAndPrint"; Name="RestrictDriverInstallationToAdministrators"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Limits print driver installation to Administrators' is set to 'Enabled'
  @{ Id="18.7.11"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Printers"; Name="CopyFilesPolicy"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Manage processing of Queue-specific files' is set to 'Enabled: Limit Queue-speci
  @{ Id="18.7.12"; Key="HKLM\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint"; Name="NoWarningNoElevationOnInstall"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Point and Print Restrictions: When installing drivers for a new connection' is s
  @{ Id="18.7.13"; Key="HKLM\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint"; Name="UpdatePromptSettings"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Point and Print Restrictions: When updating drivers for an existing connection' 
  @{ Id="18.9.3.1"; Key="HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit"; Name="ProcessCreationIncludeCmdLine_Enabled"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Include command line in process creation events' is set to 'Enabled'
  @{ Id="18.9.4.1"; Key="HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\CredSSP\Parameters"; Name="AllowEncryptionOracle"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Encryption Oracle Remediation' is set to 'Enabled: Force Updated Clients'
  @{ Id="18.9.4.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\CredentialsDelegation"; Name="AllowProtectedCreds"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Remote host allows delegation of non- exportable credentials' is set to 'Enabled
  @{ Id="18.9.7.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\Device Metadata"; Name="PreventDeviceMetadataFromNetwork"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Prevent device metadata retrieval from the Internet' is set to 'Enabled'
  @{ Id="18.9.13.1"; Key="HKLM\SYSTEM\CurrentControlSet\Policies\EarlyLaunch"; Name="DriverLoadPolicy"; Type="DWord"; Value=3; Scope="MS" }  # Ensure 'Boot-Start Driver Initialization Policy' is set to 'Enabled: Good, unknown and b
  @{ Id="18.9.19.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\System"; Name="EnableCdp"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Continue experiences on this device' is set to 'Disabled'
  @{ Id="18.9.20.1.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Printers"; Name="DisableWebPnPDownload"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Turn off downloading of print drivers over HTTP' is set to 'Enabled'
  @{ Id="18.9.20.1.5"; Key="HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer"; Name="NoWebServices"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Turn off Internet download for Web publishing and online ordering wizards' is se
  @{ Id="18.9.24.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\Kernel DMA Protection"; Name="DeviceEnumerationPolicy"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Enumeration policy for external devices incompatible with Kernel DMA Protection'
  @{ Id="18.9.26.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\System"; Name="AllowCustomSSPsAPs"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Allow Custom SSPs and APs to be loaded into LSASS' is set to 'Disabled'
  @{ Id="18.9.28.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\System"; Name="BlockUserFromShowingAccountDetailsOnSignin"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Block user from showing account details on sign-in' is set to 'Enabled'
  @{ Id="18.9.28.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\System"; Name="DontDisplayNetworkSelectionUI"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Do not display network selection UI' is set to 'Enabled'
  @{ Id="18.9.28.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\System"; Name="DisableLockScreenAppNotifications"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Turn off app notifications on the lock screen' is set to 'Enabled'
  @{ Id="18.9.28.4"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\System"; Name="AllowDomainPINLogon"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Turn on convenience PIN sign-in' is set to 'Disabled'
  @{ Id="18.9.33.6.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51"; Name="DCSettingIndex"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Require a password when a computer wakes (on battery)' is set to 'Enabled'
  @{ Id="18.9.33.6.4"; Key="HKLM\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51"; Name="ACSettingIndex"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Require a password when a computer wakes (plugged in)' is set to 'Enabled'
  @{ Id="18.9.35.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services"; Name="fAllowUnsolicited"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Configure Offer Remote Assistance' is set to 'Disabled'
  @{ Id="18.9.35.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services"; Name="fAllowToGetHelp"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Configure Solicited Remote Assistance' is set to 'Disabled'
  @{ Id="18.9.36.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Rpc"; Name="EnableAuthEpResolution"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Enable RPC Endpoint Mapper Client Authentication' is set to 'Enabled'
  @{ Id="18.9.51.1.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\W32Time\TimeProviders\NtpClient"; Name="Enabled"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Enable Windows NTP Client' is set to 'Enabled'
  @{ Id="18.10.4.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\Appx"; Name="DisablePerUserUnsignedPackagesByDefault"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Not allow per-user unsigned packages to install by default (requires explicitly 
  @{ Id="18.10.6.1"; Key="HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"; Name="MSAOptional"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Allow Microsoft accounts to be optional' is set to 'Enabled'
  @{ Id="18.10.8.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer"; Name="NoAutoplayfornonVolume"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Disallow Autoplay for non-volume devices' is set to 'Enabled'
  @{ Id="18.10.8.2"; Key="HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer"; Name="NoAutorun"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Set the default behavior for AutoRun' is set to 'Enabled: Do not execute any aut
  @{ Id="18.10.8.3"; Key="HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer"; Name="NoDriveTypeAutoRun"; Type="DWord"; Value=255; Scope="MS" }  # Ensure 'Turn off Autoplay' is set to 'Enabled: All drives'
  @{ Id="18.10.9.1.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Biometrics\FacialFeatures"; Name="EnhancedAntiSpoofing"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Configure enhanced anti-spoofing' is set to 'Enabled'
  @{ Id="18.10.13.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\CloudContent"; Name="DisableConsumerAccountStateContent"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Turn off cloud consumer account state content' is set to 'Enabled'
  @{ Id="18.10.13.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\CloudContent"; Name="DisableWindowsConsumerFeatures"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Turn off Microsoft consumer experiences' is set to 'Enabled'
  @{ Id="18.10.15.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\CredUI"; Name="DisablePasswordReveal"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Do not display the password reveal button' is set to 'Enabled'
  @{ Id="18.10.15.2"; Key="HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\CredUI"; Name="EnumerateAdministrators"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Enumerate administrator accounts on elevation' is set to 'Disabled'
  @{ Id="18.10.16.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection"; Name="AllowTelemetry"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Allow Diagnostic Data' is set to 'Enabled: Diagnostic data off (not recommended)
  @{ Id="18.10.16.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection"; Name="DisableOneSettingsDownloads"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Disable OneSettings Downloads' is set to 'Enabled'
  @{ Id="18.10.16.4"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection"; Name="DoNotShowFeedbackNotifications"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Do not show feedback notifications' is set to 'Enabled'
  @{ Id="18.10.16.5"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection"; Name="EnableOneSettingsAuditing"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Enable OneSettings Auditing' is set to 'Enabled'
  @{ Id="18.10.16.6"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection"; Name="LimitDiagnosticLogCollection"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Limit Diagnostic Log Collection' is set to 'Enabled'
  @{ Id="18.10.16.7"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection"; Name="LimitDumpCollection"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Limit Dump Collection' is set to 'Enabled'
  @{ Id="18.10.18.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\AppInstaller"; Name="EnableExperimentalFeatures"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Enable App Installer Experimental Features' is set to 'Disabled'
  @{ Id="18.10.18.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\AppInstaller"; Name="EnableHashOverride"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Enable App Installer Hash Override' is set to 'Disabled'
  @{ Id="18.10.18.4"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\AppInstaller"; Name="EnableLocalArchiveMalwareScanOverride"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Enable App Installer Local Archive Malware Scan Override' is set to 'Disabled'
  @{ Id="18.10.18.5"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\AppInstaller"; Name="EnableMSAppInstallerProtocol"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Enable App Installer ms-appinstaller protocol' is set to 'Disabled'
  @{ Id="18.10.18.6"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\AppInstaller"; Name="EnableBypassCertificatePinningForMicrosoftStore"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Enable App Installer Microsoft Store Source Certificate Validation Bypass' is se
  @{ Id="18.10.26.1.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\EventLog\Application"; Name="Retention"; Type="String"; Value="0"; Scope="MS" }  # Ensure 'Application: Control Event Log behavior when the log file reaches its maximum si
  @{ Id="18.10.26.1.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\EventLog\Application"; Name="MaxSize"; Type="DWord"; Value=32768; Scope="MS" }  # Ensure 'Application: Specify the maximum log file size (KB)' is set to 'Enabled: 32,768 
  @{ Id="18.10.26.2.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\EventLog\Security"; Name="Retention"; Type="String"; Value="0"; Scope="MS" }  # Ensure 'Security: Control Event Log behavior when the log file reaches its maximum size'
  @{ Id="18.10.26.2.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\EventLog\Security"; Name="MaxSize"; Type="DWord"; Value=196608; Scope="MS" }  # Ensure 'Security: Specify the maximum log file size (KB)' is set to 'Enabled: 196,608 or
  @{ Id="18.10.26.3.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\EventLog\Setup"; Name="Retention"; Type="String"; Value="0"; Scope="MS" }  # Ensure 'Setup: Control Event Log behavior when the log file reaches its maximum size' is
  @{ Id="18.10.26.3.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\EventLog\Setup"; Name="MaxSize"; Type="DWord"; Value=32768; Scope="MS" }  # Ensure 'Setup: Specify the maximum log file size (KB)' is set to 'Enabled: 32,768 or gre
  @{ Id="18.10.26.4.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\EventLog\System"; Name="Retention"; Type="String"; Value="0"; Scope="MS" }  # Ensure 'System: Control Event Log behavior when the log file reaches its maximum size' i
  @{ Id="18.10.26.4.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\EventLog\System"; Name="MaxSize"; Type="DWord"; Value=32768; Scope="MS" }  # Ensure 'System: Specify the maximum log file size (KB)' is set to 'Enabled: 32,768 or gr
  @{ Id="18.10.29.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer"; Name="DisableMotWOnInsecurePathCopy"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Do not apply the Mark of the Web tag to files copied from insecure sources' is s
  @{ Id="18.10.29.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer"; Name="NoDataExecutionPrevention"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Turn off Data Execution Prevention for Explorer' is set to 'Disabled'
  @{ Id="18.10.29.4"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer"; Name="NoHeapTerminationOnCorruption"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Turn off heap termination on corruption' is set to 'Disabled'
  @{ Id="18.10.29.5"; Key="HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer"; Name="PreXPSP2ShellProtocolBehavior"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Turn off shell protocol protected mode' is set to 'Disabled'
  @{ Id="18.10.42.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\MicrosoftAccount"; Name="DisableUserAuth"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Block all consumer Microsoft account user authentication' is set to 'Enabled'
  @{ Id="18.10.43.4.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Features"; Name="PassiveRemediation"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Enable EDR in block mode' is set to 'Enabled'
  @{ Id="18.10.43.5.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Spynet"; Name="LocalSettingOverrideSpynetReporting"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Configure local setting override for reporting to Microsoft MAPS' is set to 'Dis
  @{ Id="18.10.43.6.1.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR"; Name="ExploitGuard_ASR_Rules"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Configure Attack Surface Reduction rules' is set to 'Enabled'
  @{ Id="18.10.43.6.3.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\Network Protection"; Name="EnableNetworkProtection"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Prevent users and apps from accessing dangerous websites' is set to 'Enabled: Bl
  @{ Id="18.10.43.7.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\MpEngine"; Name="EnableFileHashComputation"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Enable file hash computation feature' is set to 'Enabled'
  @{ Id="18.10.43.10.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection"; Name="OobeEnableRtpAndSigUpdate"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Configure real-time protection and Security Intelligence Updates during OOBE' is
  @{ Id="18.10.43.10.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection"; Name="DisableIOAVProtection"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Scan all downloaded files and attachments' is set to 'Enabled'
  @{ Id="18.10.43.10.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection"; Name="DisableRealtimeMonitoring"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Turn off real-time protection' is set to 'Disabled'
  @{ Id="18.10.43.10.4"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection"; Name="DisableBehaviorMonitoring"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Turn on behavior monitoring' is set to 'Enabled'
  @{ Id="18.10.43.10.5"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection"; Name="DisableScriptScanning"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Turn on script scanning' is set to 'Enabled'
  @{ Id="18.10.43.11.1.1.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Remediation\Behavioral Network Blocks\Brute Force Protection"; Name="BruteForceProtectionConfiguredState"; Type="DWord"; Value=2; Scope="MS" }  # Ensure 'Configure Remote Encryption Protection Mode' is set to 'Enabled: Audit' or highe
  @{ Id="18.10.43.13.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Scan"; Name="QuickScanIncludeExclusions"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Scan excluded files and directories during quick scans' is set to 'Enabled: 1'
  @{ Id="18.10.43.13.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Scan"; Name="DisablePackedExeScanning"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Scan packed executables' is set to 'Enabled'
  @{ Id="18.10.43.13.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Scan"; Name="DisableRemovableDriveScanning"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Scan removable drives' is set to 'Enabled'
  @{ Id="18.10.43.13.4"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Scan"; Name="DaysUntilAggressiveCatchupQuickScan"; Type="DWord"; Value=7; Scope="MS" }  # Ensure 'Trigger a quick scan after X days without any scans' is set to 'Enabled: 7'
  @{ Id="18.10.43.13.5"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Scan"; Name="DisableEmailScanning"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Turn on e-mail scanning' is set to 'Enabled'
  @{ Id="18.10.43.16"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender"; Name="PUAProtection"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Configure detection for potentially unwanted applications' is set to 'Enabled: B
  @{ Id="18.10.43.17"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender"; Name="HideExclusionsFromLocalUsers"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Control whether exclusions are visible to local users' is set to 'Enabled'
  @{ Id="18.10.51.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\OneDrive"; Name="DisableFileSyncNGSC"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Prevent the usage of OneDrive for file storage' is set to 'Enabled'
  @{ Id="18.10.57.2.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services"; Name="DisablePasswordSaving"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Do not allow passwords to be saved' is set to 'Enabled'
  @{ Id="18.10.57.3.3.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services"; Name="fDisableCdm"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Do not allow drive redirection' is set to 'Enabled'
  @{ Id="18.10.57.3.9.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services"; Name="fPromptForPassword"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Always prompt for password upon connection' is set to 'Enabled'
  @{ Id="18.10.57.3.9.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services"; Name="fEncryptRPCTraffic"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Require secure RPC communication' is set to 'Enabled'
  @{ Id="18.10.57.3.9.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services"; Name="SecurityLayer"; Type="DWord"; Value=2; Scope="MS" }  # Ensure 'Require use of specific security layer for remote (RDP) connections' is set to '
  @{ Id="18.10.57.3.9.4"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services"; Name="UserAuthentication"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Require user authentication for remote connections by using Network Level Authen
  @{ Id="18.10.57.3.9.5"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services"; Name="MinEncryptionLevel"; Type="DWord"; Value=3; Scope="MS" }  # Ensure 'Set client connection encryption level' is set to 'Enabled: High Level'
  @{ Id="18.10.57.3.11.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services"; Name="DeleteTempDirsOnExit"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Do not delete temp folders upon exit' is set to 'Disabled'
  @{ Id="18.10.57.3.11.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services"; Name="PerSessionTempDir"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Do not use temporary folders per session' is set to 'Disabled'
  @{ Id="18.10.58.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Internet Explorer\Feeds"; Name="DisableEnclosureDownload"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Prevent downloading of enclosures' is set to 'Enabled'
  @{ Id="18.10.58.2"; Key="HKLM\Software\Policies\Microsoft\Internet Explorer\Feeds"; Name="AllowBasicAuthInClear"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Turn on Basic feed authentication over HTTP' is set to 'Disabled'
  @{ Id="18.10.59.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search"; Name="AllowIndexingEncryptedStoresOrItems"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Allow indexing of encrypted files' is set to 'Disabled'
  @{ Id="18.10.76.2.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\System"; Name="EnableSmartScreen"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Configure Windows Defender SmartScreen' is set to 'Enabled: Warn and prevent byp
  @{ Id="18.10.76.2.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\System"; Name="ShellSmartScreenLevel"; Type="String"; Value="Block"; Scope="MS" }  # Ensure 'Configure Windows Defender SmartScreen' is set to 'Enabled: Warn and prevent byp
  @{ Id="18.10.80.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\WindowsInkWorkspace"; Name="AllowWindowsInkWorkspace"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Allow Windows Ink Workspace' is set to 'Enabled: On, but disallow access above l
  @{ Id="18.10.81.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\Installer"; Name="EnableUserControl"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Allow user control over installs' is set to 'Disabled'
  @{ Id="18.10.81.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\Installer"; Name="AlwaysInstallElevated"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Always install with elevated privileges' is set to 'Disabled'
  @{ Id="18.10.82.1"; Key="HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"; Name="EnableMPR"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Configure the transmission of the user's password in the content of MPR notifica
  @{ Id="18.10.82.2"; Key="HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"; Name="DisableAutomaticRestartSignOn"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Sign-in and lock last interactive user automatically after a restart' is set to 
  @{ Id="18.10.89.1.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client"; Name="AllowBasic"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Allow Basic authentication' is set to 'Disabled'
  @{ Id="18.10.89.1.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client"; Name="AllowUnencryptedTraffic"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Allow unencrypted traffic' is set to 'Disabled'
  @{ Id="18.10.89.1.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client"; Name="AllowDigest"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Disallow Digest authentication' is set to 'Enabled'
  @{ Id="18.10.89.2.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service"; Name="AllowBasic"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Allow Basic authentication' is set to 'Disabled'
  @{ Id="18.10.89.2.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service"; Name="AllowUnencryptedTraffic"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Allow unencrypted traffic' is set to 'Disabled'
  @{ Id="18.10.89.2.4"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service"; Name="DisableRunAs"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Disallow WinRM from storing RunAs credentials' is set to 'Enabled'
  @{ Id="18.10.92.2.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows Defender Security Center\App and Browser protection"; Name="DisallowExploitProtectionOverride"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Prevent users from modifying settings' is set to 'Enabled'
  @{ Id="18.10.93.1.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU"; Name="NoAutoRebootWithLoggedOnUsers"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'No auto-restart with logged on users for scheduled automatic updates installatio
  @{ Id="18.10.93.2.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU"; Name="NoAutoUpdate"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Configure Automatic Updates' is set to 'Enabled'
  @{ Id="18.10.93.2.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU"; Name="ScheduledInstallDay"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Configure Automatic Updates: Scheduled install day' is set to '0 - Every day'
  @{ Id="18.10.93.4.1"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate"; Name="ManagePreviewBuildsPolicyValue"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Manage preview builds' is set to 'Disabled'
  @{ Id="18.10.93.4.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate"; Name="DeferFeatureUpdates"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Select when Preview Builds and Feature Updates are received' is set to 'Enabled:
  @{ Id="18.10.93.4.2"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate"; Name="DeferFeatureUpdatesPeriodInDays"; Type="DWord"; Value=180; Scope="MS" }  # Ensure 'Select when Preview Builds and Feature Updates are received' is set to 'Enabled:
  @{ Id="18.10.93.4.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate"; Name="DeferQualityUpdates"; Type="DWord"; Value=1; Scope="MS" }  # Ensure 'Select when Quality Updates are received' is set to 'Enabled: 0 days'
  @{ Id="18.10.93.4.3"; Key="HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate"; Name="DeferQualityUpdatesPeriodInDays"; Type="DWord"; Value=0; Scope="MS" }  # Ensure 'Select when Quality Updates are received' is set to 'Enabled: 0 days'
  @{ Id="19.5.1.1"; Key="HKCU\Software\Policies\Microsoft\Windows\CurrentVersion\PushNotifications"; Name="NoToastApplicationNotificationOnLockScreen"; Type="DWord"; Value=1; Scope="USER" }  # Ensure 'Turn off toast notifications on the lock screen' is set to 'Enabled'
  @{ Id="19.7.5.1"; Key="HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments"; Name="SaveZoneInformation"; Type="DWord"; Value=2; Scope="USER" }  # Ensure 'Do not preserve zone information in file attachments' is set to 'Disabled'
  @{ Id="19.7.5.2"; Key="HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments"; Name="ScanWithAntiVirus"; Type="DWord"; Value=3; Scope="USER" }  # Ensure 'Notify antivirus programs when opening attachments' is set to 'Enabled'
  @{ Id="19.7.8.1"; Key="HKCU\Software\Policies\Microsoft\Windows\CloudContent"; Name="ConfigureWindowsSpotlight"; Type="DWord"; Value=2; Scope="USER" }  # Ensure 'Configure Windows spotlight on lock screen' is set to 'Disabled'
  @{ Id="19.7.8.2"; Key="HKCU\Software\Policies\Microsoft\Windows\CloudContent"; Name="DisableThirdPartySuggestions"; Type="DWord"; Value=1; Scope="USER" }  # Ensure 'Do not suggest third-party content in Windows spotlight' is set to 'Enabled'
  @{ Id="19.7.26.1"; Key="HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer"; Name="NoInplaceSharing"; Type="DWord"; Value=1; Scope="USER" }  # Ensure 'Prevent users from sharing files within their profile.' is set to 'Enabled'
  @{ Id="19.7.44.1"; Key="HKCU\Software\Policies\Microsoft\Windows\Installer"; Name="AlwaysInstallElevated"; Type="DWord"; Value=0; Scope="USER" }  # Ensure 'Always install with elevated privileges' is set to 'Disabled'
)
